<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                                  <tr>
                                    <td height="26">
                                      <img src="templets/html/images/1_24_02.jpg" width="7" height="7" />       <span style="float:right">[[field:pubdate function="GetDateMK(@me)"/]]  </span>   <a href="[field:arcurl /]" title="[field:title /]">[field:title /]</a></td>
                                  </tr>
                                </table>