<div >
                                                 <div height="26">
                                                   <span style="float:right">[[field:pubdate function="GetDateMK(@me)"/]]  </span>  <img src="templets/html/images/1_24_02.jpg" width="7" height="7" />    <a href="[field:arcurl /]" title="[field:title /]">[field:title /]</a>
                                                   </div>
                                              </div>