<?php
$z[0]=Array("global","",102,129);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",141,173);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",220,246);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("myad","",301,336);
$z[3][4]['name']="innerTopBanner1";
$z[4]=Array("myad","",371,406);
$z[4][4]['name']="innerTopBanner2";
$z[5]=Array("global","",709,734);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",774,1017);
$z[6][4]['type']="top";
$z[6][4]['row']="10";
$z[6][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[7]=Array("global","",1109,1134);
$z[7][4]['name']="cfg_cmsurl";

?>