<?php
$z[0]=Array("field","",317,336);
$z[0][4]['name']="title";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",404,433);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",473,531);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",843,880);
$z[4][4]['filename']="header.htm";
$z[5]=Array("include","",885,920);
$z[5][4]['filename']="list.htm";
$z[6]=Array("field","",1324,1353);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1388,1417);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n                <tr>\r\n                  <td height=\"30\" style=\"border-bottom:1px #CCCCCC dashed; padding:0 5px;\" class=\"f12\">\r\n				  <span style=\"float:right\">[[field:pubdate function=\"GetDateMK(@me)\"/]]</span>\r\n				  <strong>&middot;</strong>&nbsp;&nbsp;&nbsp;<a href=\"[field:arcurl /]\" title=\"[field:title /]\">[field:title /]</a></td>\r\n                </tr>\r\n                ",1840,2256);
$z[8][4]['pagesize']="20";
$z[9]=Array("pagelist","",2347,2418);
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",2694,2731);
$z[10][4]['filename']="footer.htm";

?>