<?php
$z[0]=Array("arclist","\r\n                              picarr[[field:global.autoindex/]]  = \"[field:litpic/]\";\r\n\r\n                              ",3285,3463);
$z[0][4]['flag']="f";
$z[0][4]['row']="5";
$z[0][4]['typeid']="8";
$z[1]=Array("global","",4457,4487);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",4908,4938);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("arclist","\r\n                                                        <div >\r\n                                                           <div height=\"26\">\r\n                                                             <span style=\"float:right\">[[field:pubdate function=\"GetDateMK(@me)\"/]]  </span>  <img src=\"templets/html/images/1_24_02.jpg\" width=\"7\" height=\"7\" />    <a href=\"[field:arcurl /]\" title=\"[field:title /]\">[field:title /]</a>\r\n                                                             </div>\r\n                                                        </div>\r\n                                                        ",6466,7151);
$z[3][4]['titlelen']="44";
$z[3][4]['row']="10";
$z[3][4]['typeid']="2";

?>